EXPERIMENT:
  NAME: ""
  TAG: "wkd,wrn_40_2,resnet8x4,2,9"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "WKD"
  TEACHER: "wrn_40_2"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
# changed by CDK
WKD:
  INPUT_SIZE: (32, 32)
  LOSS:
    CE_WEIGHT: 1.0
    WKD_LOGIT_WEIGHT: 200.0
    WKD_FEAT_WEIGHT: 0.08
    COSINE_DECAY_EPOCH: 150
  SINKHORN:
    LAMBDA: 0.05
    ITER: 10
  COST_MATRIX: 'cka'
  COST_MATRIX_PATH: "wkd_cost_matrix/cifar100/resnet32x4/linear_cka.pth"
  COST_MATRIX_SHARPEN: 1.0
  TEMPERATURE: 8.0
  EPS: 0.00001
  HINT_LAYER: -1
  MEAN_COV_RATIO: 8.0
  PROJECTOR: "conv1x1"
  SPATIAL_GRID: 1
LOG:
  WANDB: False
  TENSORBOARD_FREQ: 10
  SAVE_CHECKPOINT_FREQ: 100